version: "1.7"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      MONGO_DB_URI: $MONGO_DB_URI
      BOT_NAME: $MUSIC_BOT_NAME
      OWNER_ID: $OWNER_ID
      SESSION_NAME: $STRING_SESSION
      DURATION_LIMIT: $DURATION_LIMIT
      UPDATE: $UPDATE
      SUPPORT: $SUPPORT
      HEROKU_API_KEY: $HEROKU_API_KEY
      HEROKU_APP_NAME: $HEROKU_APP_NAME
      START_IMG: $START_IMG_URL
      ASSID: $ASSID
      ASSNAME: $ASSNAME
      ASSUSERNAME: $ASSUSERNAME
      BOT_ID: $BOT_ID
      BOT_USERNAME: $BOT_USERNAME
      SUDO_USERS: $SUDO_USERS
